config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :books, only: %w[show]

  get '/hit_dima', to: 'hit_dima#index'
  get '/hit_dima/punch', to: 'hit_dima#punch'

  %w[404 422 500 503].each do |code|
    get code, to: 'errors#show', code:
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  paginates_per 25

  has_one :status
end

app/models/status.rb
# frozen_string_literal: true

class Status < ApplicationRecord
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
# frozen_string_literal: true

# Book controller
class BooksController < ApplicationController
  def show
    @book = Book.find_by(params[:id])
    @image_url = "https://source.unsplash.com/random/500×300/?book_cover"
  end
end

app/controllers/errors_controller.rb
# frozen_string_literal: true

# Errors controller
class ErrorsController < ApplicationController
  def show
    status_code = params[:code] || 500
    flash.alert = "Status #{status_code}"
    render status_code.to_s, status: status_code
  end
end

app/controllers/hit_dima_controller.rb
# frozen_string_literal: true

# HitDima controller
class HitDimaController < ApplicationController
  def index; end
  def punch; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# Home controller
class HomeController < ApplicationController
  def index
    @books = Book.all.page(params[:page])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application helper
module ApplicationHelper
end

app/helpers/book_helper.rb
# frozen_string_literal: true

# Book helper
module BookHelper
end

app/helpers/hit_dima_helper.rb
# frozen_string_literal: true

# HitDima Helper
module HitDimaHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

# Home helper
module HomeHelper
  def get_author_full_name(id)
    author = Author.find_by(id:)
    "#{author.middle_name} #{author.first_name} #{author.last_name}"
  end

  def get_status_name(id)
    status = Status.find_by(id:)
    status.title.to_s
  end
end

app/views/books/show.html.slim
.d-flex.justify-content-center
  h1
    | #{@book[:title]}

  img src="#{@image_url}"

app/views/hit_dima/index.html.slim
.d-flex.justify-content-center style='margin: 18rem;'
  .card style='width: 40rem;'
    .card-body
      h1.card-title.text-center
        | Вы можете послать запрос на удар кнопкой ниже!

      .card-body.text-center
        = link_to 'УДАРИТЬ', hit_dima_punch_path, class: 'btn btn-danger'

app/views/hit_dima/punch.html.erb
<div class="d-flex justify-content-center" style="margin: 6rem;">
  <%= video_tag "fight.mp4", controls: true %>
</div>

app/views/home/index.html.slim
.d-flex.justify-content-center.p-3.m-3
  h1
    | Крутая библиотека

table.table.table-striped.table-hover.mb-5
  thead
    tr
      th{ scope: :col } = 'Название книги'
      th{ scope: :col } = 'Автор книги'
      th{ scope: :col } = 'Статус'
      th{ scope: :col } = 'Год выхода книги'
      th

  tbody
    - @books.each do |book|
      tr
        td = book.title
        td = get_author_full_name(book.author_id)
        td = get_status_name(book.status_id)
        td = book.release_date
        td.d-flex
          .me-4.btn.bg-dark = link_to 'Посмотреть', book_path(book), { style: 'text-decoration: none;', class: 'text-white' }

.d-flex.justify-content-center.p-3.m-3
  = paginate @books

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Cool-Library
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/layouts/header'
    = yield

app/views/shared/layouts/_header.html.slim
nav.navbar.navbar-expand-md.navbar-dark.fixed-top.bg-dark
  .container-fluid
    .collapse.navbar-collapse
      ul.navbar-nav.me-auto.mb-2.mb-md-0
        li.nav-item
          = link_to 'Главная',
                    root_path,
                    class: 'nav-link text-decoration-none'
        li.nav-item
          = link_to '#УдарПоДмитрию',
                    hit_dima_path,
                    class: 'nav-link text-decoration-none'
        - if current_user.nil?
          li.nav-item
            = link_to 'Войти',
                      new_user_session_path,
                      class: 'nav-link text-decoration-none'
          li.nav-item
            = link_to 'Регистрация',
                      new_user_registration_path,
                      class: 'nav-link text-decoration-none'
        - else
          li.nav-item
            = link_to current_user['email'],
                      nil,
                      class: 'nav-link text-decoration-none'
          li.nav-item
            = link_to 'Выйти',
                      destroy_user_session_path,
                      class: 'nav-link text-decoration-none'